language: python
python:
  - 2.7
env:
  matrix:
    - TESTENV=py27-pytest30
    - TESTENV=py33-pytest30
    - TESTENV=py34-pytest30
install:
  - pip install -U tox
script:
  - tox --recreate -e $TESTENV
